[[session]]
name = "🏠 Home"
path = "~"

[[session]]
name = "🟢 Tomorro"
path = "~/Developer/tomorro/"
windows = ["shell"]

[[window]]
name = "run"
startup_script = "make install && make start"

[[window]]
name = "shell"
